language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - node_modules

script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://laycraft.github.io/bcgov-angular-starter-pack/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
